name: Plugin contacts UI CI

on:
  push:
    branches:
      - dev
      - staging
      - build-test
    paths:
      - 'packages/erxes-ui/**'
      - 'packages/ui-plugin-template/**'
      - 'packages/ui-cards/**'
      - 'packages/ui-forms/**'
      - 'packages/ui-inbox/**'
      - 'packages/ui-knowledgebase/**'
      - 'packages/ui-leads/**'
      - 'packages/ui-log/**'
      - 'packages/ui-notifications/**'
      - 'packages/ui-products/**'
      - 'packages/ui-segments/**'
      - 'packages/ui-settings/**'
      - 'packages/ui-team/**'
      - 'packages/ui-contacts/**'
      - 'packages/plugin-contacts-ui/**'
      - '.github/workflows/plugin-contacts-ui.yaml'
  pull_request:
    branches:
      - dev
      - staging
      - build-test
    paths:
      - 'packages/erxes-ui/**'
      - 'packages/ui-plugin-template/**'
      - 'packages/ui-cards/**'
      - 'packages/ui-forms/**'
      - 'packages/ui-inbox/**'
      - 'packages/ui-knowledgebase/**'
      - 'packages/ui-leads/**'
      - 'packages/ui-log/**'
      - 'packages/ui-notifications/**'
      - 'packages/ui-products/**'
      - 'packages/ui-segments/**'
      - 'packages/ui-settings/**'
      - 'packages/ui-team/**'
      - 'packages/ui-contacts/**'
      - 'packages/plugin-contacts-ui/**'
      - '.github/workflows/plugin-contacts-ui.yaml'

jobs:
  runtest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: setup node -v
        uses: actions/setup-node@v1
        with:
          node-version: 16.20.x
      
      - uses: actions/checkout@v2
      
      - name: docker up
        run: |
         cd docker
         docker compose up -d

      - name: yarn install & install pm2
        run: |
          sudo -i
          yarn install --save
          sudo npm install -g pm2

      - name: Run 'yarn install' in the './cli' directory. 
        run: |
          cd cli
          yarn install --save
          cp configs.json.cli.sample configs.json

      - name: Run 'yarn watch template' in the './packages/gateway' directory. 
        run: |
          cd packages/gateway
          yarn install --save
          yarn watchTemplateForCli

      - name: start with "dev --deps" 
        run: |
          cd cli
          ./bin/erxes.js dev --deps

      - run: sleep 30

      - name: "run test"
        uses: cypress-io/github-action@v5
        with:
          wait-on: "http://localhost:3000"
          wait-on-timeout: 1000
          browser: chrome
          record: true
          spec: ./cypress/tests/ui/contacts/*.cy.js
          config-file: cypress.config.js
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: "cypress:server:args"
  ui:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.20.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.20.x

      - name: Build
        run: |
          yarn install --frozen-lockfile
          cp -r packages/ui-plugin-template/.erxes packages/plugin-contacts-ui/.erxes
          cp -r packages/plugin-contacts-ui/src packages/plugin-contacts-ui/.erxes/plugin-src
          cd packages/plugin-contacts-ui
          yarn install
          yarn install-deps
          yarn build

      - name: Configure AWS credentials
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/staging')
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/build-test')
        run: |
          tar -cf build.tar --directory=packages/plugin-contacts-ui/.erxes/dist .
          cp build.tar packages/plugin-contacts-ui/.erxes/dist
          rm -rf packages/plugin-contacts-ui/.erxes/dist/*.js
          aws s3 sync packages/plugin-contacts-ui/.erxes/dist s3://erxes-${GITHUB_REF#refs/heads/}-plugins/uis/plugin-contacts-ui --delete
