name: Plugin forum Api CI

on:
  push:
    branches:
      - 'forum-fix-1.5.5'
    paths:
      - 'packages/api-utils/**'
      - 'packages/plugin-forum-api/**'
      - '.github/workflows/plugin-forum-api.yaml'
  pull_request:
    branches:
      - 'forum-fix-1.5.5'
    paths:
      - 'packages/api-utils/**'
      - 'packages/plugin-forum-api/**'
      - '.github/workflows/plugin-forum-api.yaml'

jobs:
  api:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.17.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.x

      # https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-api-plugin-forum
          restore-keys: |
            ${{ runner.os }}-yarn-api-
            ${{ runner.os }}-yarn-

      - name: Build
        run: |
          cp -r builder dist
          cd dist
          yarn install
          yarn build plugin forum

      - name: Build docker image
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/forum-fix-1.5.5')
        run: |
          cd dist/erxes
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker buildx build -t erxes/plugin-forum-api:1.5.5 -f Dockerfile .
          docker push erxes/plugin-forum-api:1.5.5
